# Generated by Django 5.1.7 on 2025-03-29 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('kvb1', 'KVB'), ('hdfc', 'HDFC'), ('icici', 'ICICI')], max_length=15)),
                ('transcation_type', models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw')], max_length=10)),
                ('purpose', models.CharField(max_length=15)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('withdraw', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('account_no', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('commission', models.FloatField(default=0)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('topup', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('balance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.passbook')),
            ],
        ),
    ]
